package common

const FAR_FUTURE_EPOCH = Epoch(^uint64(0))

const BASE_REWARDS_PER_EPOCH = 4

const DEPOSIT_CONTRACT_TREE_DEPTH = 32

const SECONDS_PER_DAY = 24 * 60 * 60

const GENESIS_SLOT Slot = 0
const GENESIS_EPOCH Epoch = 0

const JUSTIFICATION_BITS_LENGTH = 4
