//go:generate go run ../../presets/cmd/main.go --presets-dir=../../presets/eth2.0-presets --output-dir=../../presets/generated

package core

import (
	generated "github.com/protolambda/zrnt/presets/generated"
)

// Helper to know what preset is active
const PRESET_NAME = generated.PRESET_NAME

// Misc.
const SHARD_COUNT Shard = generated.SHARD_COUNT
const TARGET_COMMITTEE_SIZE = generated.TARGET_COMMITTEE_SIZE
const MAX_INDICES_PER_ATTESTATION = generated.MAX_INDICES_PER_ATTESTATION
const MIN_PER_EPOCH_CHURN_LIMIT = generated.MIN_PER_EPOCH_CHURN_LIMIT
const CHURN_LIMIT_QUOTIENT = generated.CHURN_LIMIT_QUOTIENT
const BASE_REWARDS_PER_EPOCH = generated.BASE_REWARDS_PER_EPOCH
const SHUFFLE_ROUND_COUNT uint8 = generated.SHUFFLE_ROUND_COUNT

// Deposit contract
const DEPOSIT_CONTRACT_TREE_DEPTH = generated.DEPOSIT_CONTRACT_TREE_DEPTH

// Gwei values
const MIN_DEPOSIT_AMOUNT Gwei = generated.MIN_DEPOSIT_AMOUNT
const MAX_EFFECTIVE_BALANCE Gwei = generated.MAX_EFFECTIVE_BALANCE

// unused const FORK_CHOICE_BALANCE_INCREMENT Gwei = generated.FORK_CHOICE_BALANCE_INCREMENT
const EJECTION_BALANCE Gwei = generated.EJECTION_BALANCE

const EFFECTIVE_BALANCE_INCREMENT Gwei = generated.EFFECTIVE_BALANCE_INCREMENT
const HALF_INCREMENT = generated.EFFECTIVE_BALANCE_INCREMENT / 2

// Initial values: TODO: assumed to be 0 in a lot of initializations, may just remove completely.
const GENESIS_SLOT Slot = generated.GENESIS_SLOT
const GENESIS_EPOCH = Epoch(GENESIS_SLOT / SLOTS_PER_EPOCH)

const FAR_FUTURE_EPOCH Epoch = generated.FAR_FUTURE_EPOCH

const BLS_WITHDRAWAL_PREFIX_BYTE byte = generated.BLS_WITHDRAWAL_PREFIX_BYTE

// Time parameters
const SECONDS_PER_SLOT Timestamp = generated.SECONDS_PER_SLOT
const MIN_ATTESTATION_INCLUSION_DELAY Slot = generated.MIN_ATTESTATION_INCLUSION_DELAY
const SLOTS_PER_EPOCH Slot = generated.SLOTS_PER_EPOCH
const MIN_SEED_LOOKAHEAD Epoch = generated.MIN_SEED_LOOKAHEAD
const ACTIVATION_EXIT_DELAY Epoch = generated.ACTIVATION_EXIT_DELAY
const SLOTS_PER_ETH1_VOTING_PERIOD Slot = generated.SLOTS_PER_ETH1_VOTING_PERIOD
const MIN_VALIDATOR_WITHDRAWABILITY_DELAY Epoch = generated.MIN_VALIDATOR_WITHDRAWABILITY_DELAY
const PERSISTENT_COMMITTEE_PERIOD Epoch = generated.PERSISTENT_COMMITTEE_PERIOD
const MAX_CROSSLINK_EPOCHS Epoch = generated.MAX_CROSSLINK_EPOCHS
const MIN_EPOCHS_TO_INACTIVITY_PENALTY = generated.MIN_EPOCHS_TO_INACTIVITY_PENALTY

// State list lengths
const SLOTS_PER_HISTORICAL_ROOT Slot = generated.SLOTS_PER_HISTORICAL_ROOT
const LATEST_RANDAO_MIXES_LENGTH Epoch = generated.LATEST_RANDAO_MIXES_LENGTH
const LATEST_ACTIVE_INDEX_ROOTS_LENGTH Epoch = generated.LATEST_ACTIVE_INDEX_ROOTS_LENGTH
const LATEST_SLASHED_EXIT_LENGTH Epoch = generated.LATEST_SLASHED_EXIT_LENGTH

// Reward and penalty quotients
const BASE_REWARD_QUOTIENT = generated.BASE_REWARD_QUOTIENT
const WHISTLEBLOWING_REWARD_QUOTIENT = generated.WHISTLEBLOWING_REWARD_QUOTIENT
const PROPOSER_REWARD_QUOTIENT = generated.PROPOSER_REWARD_QUOTIENT
const INACTIVITY_PENALTY_QUOTIENT = generated.INACTIVITY_PENALTY_QUOTIENT
const MIN_SLASHING_PENALTY_QUOTIENT = generated.MIN_SLASHING_PENALTY_QUOTIENT

// Max transactions per block
const MAX_PROPOSER_SLASHINGS = generated.MAX_PROPOSER_SLASHINGS
const MAX_ATTESTER_SLASHINGS = generated.MAX_ATTESTER_SLASHINGS
const MAX_ATTESTATIONS = generated.MAX_ATTESTATIONS
const MAX_DEPOSITS = generated.MAX_DEPOSITS
const MAX_VOLUNTARY_EXITS = generated.MAX_VOLUNTARY_EXITS
const MAX_TRANSFERS = generated.MAX_TRANSFERS

// Signature domains
const (
	DOMAIN_BEACON_PROPOSER BLSDomainType = generated.DOMAIN_BEACON_PROPOSER
	DOMAIN_RANDAO          BLSDomainType = generated.DOMAIN_RANDAO
	DOMAIN_ATTESTATION     BLSDomainType = generated.DOMAIN_ATTESTATION
	DOMAIN_DEPOSIT         BLSDomainType = generated.DOMAIN_DEPOSIT
	DOMAIN_VOLUNTARY_EXIT  BLSDomainType = generated.DOMAIN_VOLUNTARY_EXIT
	DOMAIN_TRANSFER        BLSDomainType = generated.DOMAIN_TRANSFER
)
